### ISSUE TITLE
Having Trouble Generating Jar/Understanding Instructions

### ISSUE THREAD

**Issue by godreborn** [hammer-83/ps5-jar-loader#4]
I'm using maven (first time) on ubuntu 20.04, while my main ps5 repo is ubuntu 22.04 (dunno if that's the problem), but I get this error: 
![image](https://github.com/user-attachments/assets/18d3f74b-8994-4320-8d0e-6bb926a0081f)

I'm pretty lost as to what to do or where the error is coming from, but here's my pom.xmls: 
[pom.zip](https://github.com/user-attachments/files/17829433/pom.zip)

that's in dumpclasspath, unless I did something wrong, which I probably did.

**Comment by hammer-83** [comment]
Couple of things to verify:
1. Are you executing `mvn package` from the root of the project?
2. Are there any modified files or unversioned files, compared to git repo state, in your local workspace?

**Comment by hammer-83** [comment]
So after starring at the attached pom.xml for a while, I think I finally see the issue. There definition of `parent` is as follows:
```xml
    <parent>
        <groupId>org.ps5jb.xploit</groupId>
        <artifactId>xploit</artifactId>
        <version>1.0-SNAPSHOT</version>
        <relativePath>../pom.xml</relativePath>
    </parent>
```

That's indeed incorrect so there is an issue in the current documentation. The `groupId` should be set to "org.ps5jb", it should not contain ".xploit" suffix.

**Comment by godreborn** [comment]
still can't get it to build.  I think there's a problem with the pom.xml that's on the root of xploit.  is this wrong?  it says group id and artifact id can't be the same, but they're not afaik.  here's that pom.xml.  also, like make clean, is there a way to clean the mvn clean package or is that what it's doing (i.e. cleaning its attempt and starting over?).  I copied the dumpclasspath from samples.  I'm not really sure what it's supposed to do, but that's what you're supposed to do right?  then modify its pom.xml and the one on the root of xploit?  thanks for all the help.
[pom.zip](https://github.com/user-attachments/files/17839110/pom.zip)

**Comment by hammer-83** [comment]
So copying a sample and modifying its identifier is only necessary if you plan on doing your own programming and creating your own JAR to send to the JAR loader. If you want to just build and send one of the existing JARs, you don't need to create a new module. Just compile as is, or simply find the JAR in the release.

The attached POM is also not syntactically correct, its id is the same as its parent reference. In the parent tag, you should have the group and artifact ids that match those of the parent pom (`org.ps5jb:parent` in this case). And the group and the artifact of the pom itself should be different.

So the root pom is `org.ps5jb:parent`, xploit module pom is `org.ps5jb:xploit` and its parent should point to the root pom, both in relative path and in matching group/artifact id. Your new module would be placed in directory `xploit/helloworld`, have group/artifact id `org.ps5jb.xploit:helloworld` and its parent would be `org.ps5jb:xploit` pointing to the xploit module.

(Using Maven nomenclature `groupId:artifactId` above)

**Comment by godreborn** [comment]
thanks.  that makes a lot more sense.  I tried building without modifying anything, but I did get an error before it completed:

![image](https://github.com/user-attachments/assets/3fbbdad9-a39f-4764-96e1-c58703cd2c57)

mvn clean package or mvn package is the correct command, right?

**Comment by godreborn** [comment]
nm, I solved it.  I changed from java-17 to java-11, and it seems to have worked:

![image](https://github.com/user-attachments/assets/6788f33d-a9e3-4a6c-97e3-c3b110661d5b)

**Comment by godreborn** [comment]
![image](https://github.com/user-attachments/assets/c073548e-38d4-45a1-8f50-3c4ae6c761af)

here it is.  thanks for all the help.  :)  btw, how do I make the contents of the iso an iso?  does it require special software for a bd iso?  or can I use this?  
![image](https://github.com/user-attachments/assets/3c43d353-8c5f-4407-99cd-cf1a146e3b7c)

do I need to iso the avchd folder or its contents?  I checked yours, and it's just the contents of the folder, so I wasn't sure if avchd specifies it's bluray or something when building the iso.  thanks again.

**Comment by godreborn** [comment]
btw, I think that "make iso" is from ps3tools by aldostools.

**Comment by hammer-83** [comment]
Ok, since everything is resolved, I will close this issue.
